"use client";

import { useState } from "react";
import toast from "react-hot-toast";
import { updateGlobalSettings } from "@/actions/admin-actions";

interface CalculationSettings {
  LEVEL3_THRESHOLD: string;
  LEVEL2_THRESHOLD: string;
  LEVEL1_THRESHOLD: string;
  DIRECT_ENDSEM_WEIGHT: string;
  DIRECT_INTERNAL_WEIGHT: string;
  FINAL_DIRECT_WEIGHT: string;
  FINAL_INDIRECT_WEIGHT: string;
}

const DEFAULTS: CalculationSettings = {
  LEVEL3_THRESHOLD: "65",
  LEVEL2_THRESHOLD: "50",
  LEVEL1_THRESHOLD: "35",
  DIRECT_ENDSEM_WEIGHT: "0.7",
  DIRECT_INTERNAL_WEIGHT: "0.3",
  FINAL_DIRECT_WEIGHT: "0.8",
  FINAL_INDIRECT_WEIGHT: "0.2",
};

export default function CalculationSettingsManager({ initialSettings }: { initialSettings: Record<string, string> }) {
  const [settings, setSettings] = useState<CalculationSettings>({
    LEVEL3_THRESHOLD: initialSettings.LEVEL3_THRESHOLD || DEFAULTS.LEVEL3_THRESHOLD,
    LEVEL2_THRESHOLD: initialSettings.LEVEL2_THRESHOLD || DEFAULTS.LEVEL2_THRESHOLD,
    LEVEL1_THRESHOLD: initialSettings.LEVEL1_THRESHOLD || DEFAULTS.LEVEL1_THRESHOLD,
    DIRECT_ENDSEM_WEIGHT: initialSettings.DIRECT_ENDSEM_WEIGHT || DEFAULTS.DIRECT_ENDSEM_WEIGHT,
    DIRECT_INTERNAL_WEIGHT: initialSettings.DIRECT_INTERNAL_WEIGHT || DEFAULTS.DIRECT_INTERNAL_WEIGHT,
    FINAL_DIRECT_WEIGHT: initialSettings.FINAL_DIRECT_WEIGHT || DEFAULTS.FINAL_DIRECT_WEIGHT,
    FINAL_INDIRECT_WEIGHT: initialSettings.FINAL_INDIRECT_WEIGHT || DEFAULTS.FINAL_INDIRECT_WEIGHT,
  });
  const [isSaving, setIsSaving] = useState(false);

  const handleChange = (key: keyof CalculationSettings, value: string) => {
    setSettings(prev => ({ ...prev, [key]: value }));
  };

  const handleSave = async () => {
    // Validate thresholds
    const l3 = parseFloat(settings.LEVEL3_THRESHOLD);
    const l2 = parseFloat(settings.LEVEL2_THRESHOLD);
    const l1 = parseFloat(settings.LEVEL1_THRESHOLD);
    if (isNaN(l3) || isNaN(l2) || isNaN(l1) || l3 <= l2 || l2 <= l1 || l1 <= 0) {
      toast.error("Thresholds must be numbers in descending order: Level 3 > Level 2 > Level 1 > 0");
      return;
    }

    // Validate direct weights sum to 1
    const endW = parseFloat(settings.DIRECT_ENDSEM_WEIGHT);
    const intW = parseFloat(settings.DIRECT_INTERNAL_WEIGHT);
    if (isNaN(endW) || isNaN(intW) || Math.abs(endW + intW - 1) > 0.01) {
      toast.error("End Sem + Internal weights must sum to 1.0");
      return;
    }

    // Validate final weights sum to 1
    const dirW = parseFloat(settings.FINAL_DIRECT_WEIGHT);
    const indW = parseFloat(settings.FINAL_INDIRECT_WEIGHT);
    if (isNaN(dirW) || isNaN(indW) || Math.abs(dirW + indW - 1) > 0.01) {
      toast.error("Direct + Indirect weights must sum to 1.0");
      return;
    }

    setIsSaving(true);
    const res = await updateGlobalSettings(settings as unknown as Record<string, string>);
    if (res.success) {
      toast.success("Calculation parameters updated! New reports will use these values.");
    } else {
      toast.error(res.error || "Failed to save");
    }
    setIsSaving(false);
  };

  const handleReset = () => {
    setSettings({ ...DEFAULTS });
    toast.success("Reset to NBA defaults (not saved yet — click Save to apply)");
  };

  return (
    <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200 mt-8 space-y-6">
      <div className="flex justify-between items-start">
        <div>
          <h2 className="text-xl font-semibold text-gray-800">CO-PO Attainment Calculation Parameters</h2>
          <p className="text-gray-500 text-sm mt-1">These formulas directly drive every CO attainment level and PO attainment result generated by the system.</p>
        </div>
        <button onClick={handleReset} className="text-xs px-3 py-1.5 bg-gray-100 text-gray-600 rounded hover:bg-gray-200 border border-gray-300 font-medium">
          Reset to NBA Defaults
        </button>
      </div>

      {/* Section 1: Attainment Level Thresholds */}
      <div className="border border-blue-200 rounded-lg p-5 bg-blue-50/40">
        <h3 className="text-sm font-bold text-blue-900 mb-1">1. Attainment Level Thresholds (% of Max Marks)</h3>
        <p className="text-xs text-blue-700 mb-4">When a student scores at or above these percentages, they are assigned the corresponding attainment level.</p>
        
        <div className="bg-white rounded border border-blue-200 overflow-hidden">
          <div className="grid grid-cols-[1fr_100px_120px] bg-blue-100 text-xs font-bold text-blue-900 uppercase tracking-wider">
            <div className="p-3">Condition</div>
            <div className="p-3 text-center">Threshold (%)</div>
            <div className="p-3 text-center">→ Level</div>
          </div>
          <div className="grid grid-cols-[1fr_100px_120px] border-b border-blue-100 items-center">
            <div className="p-3 text-sm text-gray-700">Percentage <span className="font-bold">≥</span></div>
            <div className="p-3">
              <input type="number" value={settings.LEVEL3_THRESHOLD} onChange={e => handleChange('LEVEL3_THRESHOLD', e.target.value)}
                className="w-full px-2 py-1.5 border rounded text-center text-sm font-bold focus:ring-blue-500" />
            </div>
            <div className="p-3 text-center">
              <span className="inline-block px-3 py-1 bg-green-100 text-green-800 font-bold text-sm rounded border border-green-300">Level 3</span>
            </div>
          </div>
          <div className="grid grid-cols-[1fr_100px_120px] border-b border-blue-100 items-center">
            <div className="p-3 text-sm text-gray-700">Percentage <span className="font-bold">≥</span></div>
            <div className="p-3">
              <input type="number" value={settings.LEVEL2_THRESHOLD} onChange={e => handleChange('LEVEL2_THRESHOLD', e.target.value)}
                className="w-full px-2 py-1.5 border rounded text-center text-sm font-bold focus:ring-blue-500" />
            </div>
            <div className="p-3 text-center">
              <span className="inline-block px-3 py-1 bg-yellow-100 text-yellow-800 font-bold text-sm rounded border border-yellow-300">Level 2</span>
            </div>
          </div>
          <div className="grid grid-cols-[1fr_100px_120px] border-b border-blue-100 items-center">
            <div className="p-3 text-sm text-gray-700">Percentage <span className="font-bold">≥</span></div>
            <div className="p-3">
              <input type="number" value={settings.LEVEL1_THRESHOLD} onChange={e => handleChange('LEVEL1_THRESHOLD', e.target.value)}
                className="w-full px-2 py-1.5 border rounded text-center text-sm font-bold focus:ring-blue-500" />
            </div>
            <div className="p-3 text-center">
              <span className="inline-block px-3 py-1 bg-orange-100 text-orange-800 font-bold text-sm rounded border border-orange-300">Level 1</span>
            </div>
          </div>
          <div className="grid grid-cols-[1fr_100px_120px] items-center bg-gray-50">
            <div className="p-3 text-sm text-gray-500">Below Level 1 Threshold</div>
            <div className="p-3 text-center text-gray-400 text-sm">—</div>
            <div className="p-3 text-center">
              <span className="inline-block px-3 py-1 bg-red-100 text-red-800 font-bold text-sm rounded border border-red-300">Level 0</span>
            </div>
          </div>
        </div>
      </div>

      {/* Section 2: Overall Direct Attainment Formula */}
      <div className="border border-purple-200 rounded-lg p-5 bg-purple-50/40">
        <h3 className="text-sm font-bold text-purple-900 mb-1">2. Overall Direct CO Attainment Formula</h3>
        <p className="text-xs text-purple-700 mb-4">Combines End Semester and Internal assessment to compute the Direct Attainment for each CO.</p>
        
        <div className="bg-white rounded border border-purple-200 p-4">
          <div className="flex items-center gap-3 flex-wrap justify-center">
            <span className="text-sm font-semibold text-gray-700">Direct Attainment =</span>
            <span className="text-sm text-gray-500">(End Sem Level ×</span>
            <input type="number" step="0.01" value={settings.DIRECT_ENDSEM_WEIGHT} onChange={e => handleChange('DIRECT_ENDSEM_WEIGHT', e.target.value)}
              className="w-20 px-2 py-1.5 border rounded text-center text-sm font-bold focus:ring-purple-500" />
            <span className="text-sm text-gray-500">) + (Internal Level ×</span>
            <input type="number" step="0.01" value={settings.DIRECT_INTERNAL_WEIGHT} onChange={e => handleChange('DIRECT_INTERNAL_WEIGHT', e.target.value)}
              className="w-20 px-2 py-1.5 border rounded text-center text-sm font-bold focus:ring-purple-500" />
            <span className="text-sm text-gray-500">)</span>
          </div>
          <p className="text-xs text-center text-purple-600 mt-3 font-medium">⚠️ Both weights must sum to 1.0</p>
        </div>
      </div>

      {/* Section 3: Final Course Attainment Formula */}
      <div className="border border-teal-200 rounded-lg p-5 bg-teal-50/40">
        <h3 className="text-sm font-bold text-teal-900 mb-1">3. Final Course Attainment Formula</h3>
        <p className="text-xs text-teal-700 mb-4">Combines Direct Attainment with Indirect Attainment (survey/feedback) to compute the final CO attainment.</p>
        
        <div className="bg-white rounded border border-teal-200 p-4">
          <div className="flex items-center gap-3 flex-wrap justify-center">
            <span className="text-sm font-semibold text-gray-700">Final Attainment =</span>
            <span className="text-sm text-gray-500">(Direct Level ×</span>
            <input type="number" step="0.01" value={settings.FINAL_DIRECT_WEIGHT} onChange={e => handleChange('FINAL_DIRECT_WEIGHT', e.target.value)}
              className="w-20 px-2 py-1.5 border rounded text-center text-sm font-bold focus:ring-teal-500" />
            <span className="text-sm text-gray-500">) + (Indirect Level ×</span>
            <input type="number" step="0.01" value={settings.FINAL_INDIRECT_WEIGHT} onChange={e => handleChange('FINAL_INDIRECT_WEIGHT', e.target.value)}
              className="w-20 px-2 py-1.5 border rounded text-center text-sm font-bold focus:ring-teal-500" />
            <span className="text-sm text-gray-500">)</span>
          </div>
          <p className="text-xs text-center text-teal-600 mt-3 font-medium">⚠️ Both weights must sum to 1.0</p>
        </div>
      </div>

      {/* Section 4: PO Attainment (read-only explanation) */}
      <div className="border border-gray-200 rounded-lg p-5 bg-gray-50/40">
        <h3 className="text-sm font-bold text-gray-800 mb-1">4. PO Attainment Calculation (Weighted Average)</h3>
        <p className="text-xs text-gray-600 mb-3">PO Attainment is derived from the CO-PO Mapping Matrix. For each PO:</p>
        <div className="bg-white rounded border border-gray-200 p-4 text-sm text-gray-700 font-mono text-center">
          PO Attainment = Σ (CO Attainment × Mapping Weight) / Σ (Mapping Weight)
        </div>
        <p className="text-xs text-gray-500 mt-2">This uses the mapping values (0-3) set by faculty in the CO-PO Matrix page. No additional parameters needed.</p>
      </div>

      <div className="pt-4 flex justify-end gap-3">
        <button onClick={handleSave} disabled={isSaving}
          className="px-6 py-2.5 bg-slate-900 text-white font-medium rounded hover:bg-slate-800 transition shadow">
          {isSaving ? "Saving..." : "Save Calculation Parameters"}
        </button>
      </div>
    </div>
  );
}
